### ISSUE TITLE
Implement the editor

### ISSUE THREAD

**Issue by actisPRO** [AlbertCerfeda/DoX#14]
* Use prosemirror instead of editor.js

**Comment by AlbertCerfeda** [comment]
@actisPRO 
In `edit.ejs`, you can safely assume that there is a parameter object `doc` containing the data of the document, as it is stored in the database.

**Comment by actisPRO** [comment]
> @actisPRO In `edit.ejs`, you can assume that there is a parameter object `doc` containing the data of the document, as it is stored in the database.

okay, thanks for the info
